# Generated by Django 4.1.2 on 2022-11-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_aposta_delete_apostador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='placar1',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='placar2',
        ),
        migrations.AddField(
            model_name='aposta',
            name='placar1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aposta',
            name='placar2',
            field=models.IntegerField(null=True),
        ),
    ]
