# Generated by Django 4.1.2 on 2022-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0003_remove_partida_placar1_remove_partida_placar2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='placar1',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='placar2',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
