# Generated by Django 4.1.2 on 2022-11-01 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_alter_aposta_placar1_alter_aposta_placar2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='jogo',
        ),
        migrations.AddField(
            model_name='equipe',
            name='placarAposta1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placarAposta1', to='bolao.aposta'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='placarAposta2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placarAposta2', to='bolao.aposta'),
        ),
        migrations.AddField(
            model_name='partida',
            name='aposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aposta', to='bolao.aposta'),
        ),
    ]
