# Generated by Django 4.1.2 on 2022-11-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0005_remove_aposta_jogo_equipe_placaraposta1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='aposta',
        ),
        migrations.AddField(
            model_name='aposta',
            name='jogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogo', to='bolao.partida'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='placarAposta1',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='placarAposta2',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
