# Generated by Django 4.1.2 on 2022-11-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0006_remove_partida_aposta_aposta_jogo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='placarAposta1',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='placarAposta2',
        ),
    ]
