# Generated by Django 4.1.2 on 2022-11-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0008_remove_aposta_valor_partida_valoraposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGrupo', models.CharField(max_length=10, null=True, unique=True, verbose_name='Nome Grupo')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grupo', to='bolao.grupos', unique=True),
        ),
    ]
