# Generated by Django 4.1.2 on 2022-11-04 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0009_grupos_equipe_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grupo', to='bolao.grupos'),
        ),
    ]
